### ISSUE TITLE
swap error while the same swap work in web app

### ISSUE THREAD

**Issue by limitspro** [cosmology-finance/cosmology#5]
use this cmd to swap
```
cosmology swap \
    --chainId osmosis-1 \
    --restEndpoint https://lcd-osmosis.blockapsis.com/ \
    --rpcEndpoint https://osmosis.validator.network/ \
    --sell UST \
    --buy ATOM \
    --value 0.1 \
    --slippage 1  
```
TX failed:
failed to execute message; message index: 0: ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2 token is lesser than min amount: calculated amount is lesser than min amount
TX: https://www.mintscan.io/osmosis/txs/F08A98B4F7932CDB3722FADF924B321A8FE0F34589485E40ADB513D7F70378A2

while the same swap succ at app, also using this cmd to swap atom/osmo succ, but swap ust would occur this error

**Comment by pyramation** [comment]
this is likely an issue with a lower slippage value at 1% in the `UST` pool being a low-liquidity and potentially unreliable pool now after it's liquidity is been depooled.

**Comment by pyramation** [comment]
If you get this for other pools, please re-open, thanks!
